-- MySQL Script generated by MySQL Workbench
-- 09/30/16 23:19:24
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sale
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sale` ;
CREATE SCHEMA IF NOT EXISTS `sale` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `sale` ;

-- -----------------------------------------------------
-- Table `sale`.`branch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sale`.`branch` ;

CREATE TABLE IF NOT EXISTS `sale`.`branch` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NULL,
  `create_date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sale`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sale`.`user` ;

CREATE TABLE IF NOT EXISTS `sale`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `address` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `is_active` BIT NOT NULL DEFAULT 1,
  `birthday` DATE NULL,
  `create_date` DATETIME NULL,
  `branch_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `branch_id`),
  CONSTRAINT `fk_user_branch`
    FOREIGN KEY (`branch_id`)
    REFERENCES `sale`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_user_branch_idx` ON `sale`.`user` (`branch_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
